name: google-sheets
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - numexpr=2.14.1
  - numpy=2.4.1
  - numpy-base=2.4.1
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=25.3
  - python=3.14.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.3
  - six=1.17.0
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025b
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - gspread==6.2.1
      - idna==3.11
      - oauthlib==3.3.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - urllib3==2.6.3
prefix: /opt/anaconda3/envs/google-sheets
