#The config file for the JV Sequencing Runs Master Sheet
sheets_to_combine: # format [spreadsheet_id, sheet_name]
  - []
  - []
  - []
  - []
  - []
  - []
  - []
  - []
  - []
  - []
  - []

destination_spreadsheet_id: 
destination_sheet_name: 